### ISSUE TITLE
jemalloc 5.1.0 causing problems with uglifier/execjs on heroku

### ISSUE THREAD

**Issue by concept47** [jemalloc/jemalloc#1313]
Not sure if this is the right place to put this (please close if it isn't), but [the jemalloc buildpack we use on heroku](https://github.com/gaffneyc/heroku-buildpack-jemalloc) has been running against 5.0.1. It recently got bumped to 5.1.0, and almost immediately, we started getting failures in the release phase of our heroku deploys that look like this

      rake aborted!
      JSON::ParserError: 765: unexpected token at 'node[29]: pthread_create: Invalid argument
      ["ok"]'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:68:in `extract_result'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
      /app/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.10/lib/uglifier.rb:154:in `initialize'
      /app/config/environments/staging.rb:21:in `new'
      /app/config/environments/staging.rb:21:in `block in <main>'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/railtie.rb:209:in `instance_eval'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/railtie.rb:209:in `configure'
      /app/config/environments/staging.rb:1:in `<main>'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `block in require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:599:in `each'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:599:in `block in <class:Engine>'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `each'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `tsort_each_child'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
      /app/config/environment.rb:5:in `<main>'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `block in require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require_environment!'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/application.rb:448:in `block in run_tasks_blocks'
      /app/vendor/bundle/ruby/2.5.0/gems/bugsnag-5.0.1/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
      Tasks: TOP => db:migrate => environment
      (See full trace by running task with --trace)

The line in question in staging.rb that seems to fail is this one

         config.assets.js_compressor = Uglifier.new(harmony: true)

All our deploys with the jemalloc buildpack removed work just fine. (Figured this because our review apps don't use jemalloc, but it seemed that we had to run 

    heroku plugins:install heroku-repo
    heroku repo:purge_cache

To get it to work. Just wanted to know if this was a jemalloc bug or if I should take it up with the uglifier/execjs folks. 

Thanks!

**Comment by davidtgoldblatt** [comment]
My memory is that there's an issue where an increase in jemalloc thread-local space usage causes a problem with earlier ruby versions (I regard it as a ruby bug -- they severely limit one of their thread stack sizes in a way that imposes limits on libraries they want to support linking against). I think later versions have a fix -- that might be the easiest thing to do. #1006 was the issue.

It seems like maybe someone is parsing command-line output, and doesn't expect the pthread error? That would imply stdout and stderr getting mixed somehow.

**Comment by concept47** [comment]
Thanks @davidtgoldblatt! I noticed you talked about earlier ruby versions, do you think this could be an issue with Ruby 2.5.0 as well? Thank you for your feedback I'll parlay it to the maintainer of the buildpack

**Comment by davidtgoldblatt** [comment]
Unfortunately, I don't totally remember. The version 2.5 does ring a bell, but I'm not sure if it's because it was the last version with the problem or the first one without it (or I could just be completely misremembering, and this could all be wrong).

**Comment by gaffneyc** [comment]
Following up on this issue since I'm the maintainer of the Heroku buildpack this was coming from.

The issue appears to be with NodeJS and not Ruby. We have a report on gaffneyc/heroku-buildpack-jemalloc#2 of NodeJS printing out `node[16]: pthread_create: Invalid argument` on STDOUT but otherwise working correctly. This started with JEMalloc 5.1.0 and wasn't the case on 5.0.1.

I'm not sure if it's a NodeJS issue or JEMalloc issue, but it seems like it would be an API regression in JEMalloc.

**Comment by hopsoft** [comment]
Verified @gaffneyc's fix on one of my Dokku deployments. Explicitly setting `JEMALLOC_VERSION` got me past the `pthread_create` error.

```sh
dokku config:set myapp JEMALLOC_VERSION=5.0.1
```

**Comment by gaffneyc** [comment]
@hopsoft I'm going to try to recreate this, which version of NodeJS were you using?

**Comment by hopsoft** [comment]
Here's the `.buildpacks` config I'm using.

```
https://github.com/gaffneyc/heroku-buildpack-jemalloc.git
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-ruby.git
```

Here's the Node version specified in `package.json`

```javascript
{
  "engines": {
    "node": "9.11.2",
    "yarn": "1.9.4"
  }
}
```

**Comment by interwq** [comment]
Let us know if you guys have more info or how we can help. The message itself doesn't ring any bell. The `pthread_create` function shouldn't be invoked with the default config, unless lazy-lock or background_thread is enabled.

**Comment by gaffneyc** [comment]
Does jemalloc redefine `pthread_create`? Based on the message I would assume it is coming from NodeJS calling `pthread_create` and not inside jemalloc itself. The buildpack doesn't enable any of the optional features (like background_thread or lazy-lock).

**Comment by interwq** [comment]
@gaffneyc : we only redefine if `LAZY_LOCK` is used -- https://github.com/jemalloc/jemalloc/blob/dev/src/mutex.c#L32
If you have a quick repro, bisecting between 5.0.1 and 5.1 may be easier.

**Comment by gaffneyc** [comment]
I've been able to reproduce the issue and it seems like there are a couple things interacting. We have seen it on Heroku using their heroku-16 stack (based on Ubuntu 16.04) but it appears fixed on their newer heroku-18 stack (based on Ubuntu 18.04). Additionally, it affects NodeJS 10.x but appears addressed in NodeJS 12.x. Lastly, we are still receiving the warning with NodeJS 10.x on heroku-16 with the latest commit to dev (https://github.com/jemalloc/jemalloc/commit/40a3435b8dc225ad61329aca89d9c8d0dfbc03ab)

I've created an easily deployable Heroku app that shows the issue: [here](https://github.com/gaffneyc/heroku-buildpack-jemalloc-issue-3)

With that application I was able to bisect jemalloc and it appears this is the commit that introduced the warning message: https://github.com/jemalloc/jemalloc/commit/9c0549007dcb64f4ff35d37390a9a6a8d3cea880

I'm not overly familiar with C and not at all familiar with jemalloc's source but I'm happy to try out potential fixes.

**Comment by interwq** [comment]
@gaffneyc: to confirm, the warning message you got with 9c05490 is about the `pthread_create: Invalid argument`? That commit doesn't seem to touch anything pthread_create related; also no initialization related change I can think of (honestly I still don't understand the issue). cc: @davidtgoldblatt

**Comment by gaffneyc** [comment]
@interwq Yes, that is the warning we're seeing and I'm not sure what to make of it either. I've tried to debug with `LD_DEBUG=all` and it is using `pthread_create` from libpthread.

```
           4: symbol=pthread_create;  lookup in file=node [0]
           4: symbol=pthread_create;  lookup in file=/app/vendor/jemalloc/lib/libjemalloc.so.2 [0]
           4: symbol=pthread_create;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
           4: symbol=pthread_create;  lookup in file=/lib/x86_64-linux-gnu/librt.so.1 [0]
           4: symbol=pthread_create;  lookup in file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
           4: symbol=pthread_create;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
           4: symbol=pthread_create;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
           4: symbol=pthread_create;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
           4: binding file node [0] to /lib/x86_64-linux-gnu/libpthread.so.0 [0]: normal symbol `pthread_create' [GLIBC_2.2.5]
```

**Comment by davidtgoldblatt** [comment]
> possibly the fields added in tcache pushed the thread-local space over some threshold

This has happened before with Ruby I recall - the interpreter set the stack for a timing thread to something small, and all thread-local state counted against it. I think that may have errored out with EINVAL, too.

**Comment by davidtgoldblatt** [comment]
Oh wait, I mentioned that upthread, and had been discussed.

How easy is this to repro? I can try poking around at the nodejs internals if the steps are easy enough.

**Comment by interwq** [comment]
@gaffneyc mentioned this was fixed in heroku-18; I'm gussing it was indeed the thread stack size on pthread_create got adjusted. Closing but feel free to ask if anything.

**Comment by gaffneyc** [comment]
It's fixed in heroku-18 but we have some people still running on heroku-16 and it would be nice to provide a usable build for them since they'll be supporting it for at least the next two years.

If it is a stack size issue, do you know of any way to change it at compile time?

**Comment by interwq** [comment]
@gaffneyc -- I'd say tracking down the failed pthread_create call, and drop the attribute to limit the stack size of the thread should fix it; that is if you can patch heroku-16 or the source of the specific pthread create.

On jemalloc side, reducing thread local usage would be a bit hard and doesn't sound the right solution here; there is the config option `--disable-initial-exec-tls` which can workaround this at a small overhead of thread local access, see details in https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md.

**Comment by gaffneyc** [comment]
Unfortunately there isn't much we can do to debug on Heroku itself and I haven't been able to recreate it locally. I will try to debug as best I can when I can find the time. I will update the ticket if I can get any more details.

By the way, I've tried a build with `--disable-initial-exec-tls` and I am still seeing the warning.

**Comment by interwq** [comment]
If `--disable-initial-exec-tls` didn't help, it's probably a different issue. Let us know if we can help @gaffneyc.

**Comment by gaffneyc** [comment]
I've been able to do more research on the issue and it does appear to be something with thread stack size. It was fixed in NodeJS 12.4.0 by [this commit](https://github.com/nodejs/node/pull/27855) which tries to set the stack size to the larger of `PTHREAD_STACK_MIN` (16384 on both 16.04 and 18.04) or 32768. It also adds a guard that PTHREAD_STACK_MIN is defined that I haven't been able to test that it's true in the context.

That's all I've been able to figure out. Neither C or C++ are my area of expertise so I don't think I can go further with this. On the one hand it seems like it is an issue with how NodeJS was creating this thread. On the other hand, if jemalloc causes PTHREAD_STACK_MIN to not actually be large enough then could it be causing other issues (and we're just seeing this because NodeJS logs it)?

**Comment by concept47** [comment]
Amazing to be able to track it that far @gaffneyc. Thanks for your hard work on this!
