### ISSUE TITLE
Various compiler warnings

### ISSUE THREAD

**Issue by rvandermeulen** [jemalloc/jemalloc#484]
On rev 4752a54, I see the following build warnings:

**MSVC2015u3**
include/jemalloc/internal/jemalloc_internal.h(835): warning C4146: unary minus operator applied to unsigned type, result still unsigned
include/jemalloc/internal/jemalloc_internal.h(1089): warning C4146: unary minus operator applied to unsigned type, result still unsigned
src/arena.c(2654): warning C4146: unary minus operator applied to unsigned type, result still unsigned
src/chunk.c(240): warning C4146: unary minus operator applied to unsigned type, result still unsigned
src/chunk_dss.c(138): warning C4146: unary minus operator applied to unsigned type, result still unsigned
src/chunk_mmap.c(22): warning C4146: unary minus operator applied to unsigned type, result still unsigned

**clang 3.8.0 (OSX build)**
/src/arena.c:70:1527: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:2803: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:4608: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:5884: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:8315: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:9591: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:16194: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:17470: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:19275: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:20551: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:22982: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:24258: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:29608: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:30884: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:32689: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:33965: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:36396: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:37672: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:40242: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:41518: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:43323: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:44599: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:47030: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:48306: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:53663: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:54939: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:56744: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:58020: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:60451: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:61727: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:64086: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:65362: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:67167: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:68443: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:70874: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]
/src/arena.c:70:72150: warning: explicitly assigning value of variable of type 'arena_chunk_map_misc_t *' (aka 'struct arena_chunk_map_misc_s *') to itself [-Wself-assign]

Warning: -Wtautological-compare in /src/jemalloc.c: comparison of unsigned expression < 0 is always false
/src/jemalloc.c:1230:327: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if ((sizeof("quarantine")-1 == klen && strncmp("quarantine", k, klen) == 0)) { uintmax_t um; char *end; je_set_errno(0); um = je_malloc_strtoumax(v, &end, 0); if (je_get_errno() != 0 || (uintptr_t)end - (uintptr_t)v != vlen) { malloc_conf_error( "Invalid conf value", k, klen, v, vlen); } else if (0) { if ((0) != 0 && um < (0)) je_opt_quarantine = (size_t)(0); else if (um > ((9223372036854775807L *2UL+1UL))) je_opt_quarantine = (size_t)((9223372036854775807L *2UL+1UL)); else je_opt_quarantine = (size_t)um; } else { if (((0) != 0 && um < (0)) || um > ((9223372036854775807L *2UL+1UL))) { malloc_conf_error( "Out-of-range " "conf value", k, klen, v, vlen); } else je_opt_quarantine = (size_t)um; } continue; }
Warning: -Wtautological-compare in /src/jemalloc.c: comparison of unsigned expression < 0 is always false
/src/jemalloc.c:1230:545: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if ((sizeof("quarantine")-1 == klen && strncmp("quarantine", k, klen) == 0)) { uintmax_t um; char *end; je_set_errno(0); um = je_malloc_strtoumax(v, &end, 0); if (je_get_errno() != 0 || (uintptr_t)end - (uintptr_t)v != vlen) { malloc_conf_error( "Invalid conf value", k, klen, v, vlen); } else if (0) { if ((0) != 0 && um < (0)) je_opt_quarantine = (size_t)(0); else if (um > ((9223372036854775807L *2UL+1UL))) je_opt_quarantine = (size_t)((9223372036854775807L *2UL+1UL)); else je_opt_quarantine = (size_t)um; } else { if (((0) != 0 && um < (0)) || um > ((9223372036854775807L *2UL+1UL))) { malloc_conf_error( "Out-of-range " "conf value", k, klen, v, vlen); } else je_opt_quarantine = (size_t)um; } continue; }
Warning: -Wtautological-compare in /src/jemalloc.c: comparison of unsigned expression < 0 is always false
/src/jemalloc.c:1267:335: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if ((sizeof("lg_prof_sample")-1 == klen && strncmp("lg_prof_sample", k, klen) == 0)) { uintmax_t um; char *end; je_set_errno(0); um = je_malloc_strtoumax(v, &end, 0); if (je_get_errno() != 0 || (uintptr_t)end - (uintptr_t)v != vlen) { malloc_conf_error( "Invalid conf value", k, klen, v, vlen); } else if (1) { if ((0) != 0 && um < (0)) je_opt_lg_prof_sample = (size_t)(0); else if (um > ((sizeof(uint64_t) << 3) - 1)) je_opt_lg_prof_sample = (size_t)((sizeof(uint64_t) << 3) - 1); else je_opt_lg_prof_sample = (size_t)um; } else { if (((0) != 0 && um < (0)) || um > ((sizeof(uint64_t) << 3) - 1)) { malloc_conf_error( "Out-of-range " "conf value", k, klen, v, vlen); } else je_opt_lg_prof_sample = (size_t)um; } continue; }
Warning: -Wtautological-compare in /src/jemalloc.c: comparison of unsigned expression < 0 is always false
/src/jemalloc.c:1267:557: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if ((sizeof("lg_prof_sample")-1 == klen && strncmp("lg_prof_sample", k, klen) == 0)) { uintmax_t um; char *end; je_set_errno(0); um = je_malloc_strtoumax(v, &end, 0); if (je_get_errno() != 0 || (uintptr_t)end - (uintptr_t)v != vlen) { malloc_conf_error( "Invalid conf value", k, klen, v, vlen); } else if (1) { if ((0) != 0 && um < (0)) je_opt_lg_prof_sample = (size_t)(0); else if (um > ((sizeof(uint64_t) << 3) - 1)) je_opt_lg_prof_sample = (size_t)((sizeof(uint64_t) << 3) - 1); else je_opt_lg_prof_sample = (size_t)um; } else { if (((0) != 0 && um < (0)) || um > ((sizeof(uint64_t) << 3) - 1)) { malloc_conf_error( "Out-of-range " "conf value", k, klen, v, vlen); } else je_opt_lg_prof_sample = (size_t)um; } continue; }

**Comment by jasone** [comment]
I resolved all the avoidable MSVC warnings on the dev branch (48d4adfbeb32fcc7f455547d89641cd1fc459361, 17aa187f6b3c5c320653167acf1e85d3d8645e62, 44df4a45cf587db8adee7edff4acfb96bfd3d670, 977103c897225a4ab0380f09adc67b4c43143521), and chose not to backport them to the rel-4.3.0 branch since none of them appear to be serious, and 977103c897225a4ab0380f09adc67b4c43143521 would have required a major rework for rel-4.3.0.

Regarding the clang 3.8.0 (OS X) warnings, I updated a machine to OS X 10.12 today to reproduce these, and although I ended up fixing several other issues (31db315f17a48380d11d5dd67dde154adf571573,  a99e0fa2d21917cbcefd8b7a9a2128ae0399d88f, 3f2b8d9cfaebdf0565da3f1ea6e8af11874eae8f, da206df10bc51f547d05563ebf17291f3f9471b0), none of these warnings reproduce with the clang that comes with XCode 8.1:

  ```
  > clang --version
  Apple LLVM version 8.0.0 (clang-800.0.42.1)
  Target: x86_64-apple-darwin16.0.0
  Thread model: posix
  InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
  > EXTRA_CFLAGS="-Wself-assign -Wtautological-compare -Wall" CC=clang ./autogen.sh && make all tests
[no warnings]
  ```

What did you do differently to produce the clang warnings?

**Comment by rvandermeulen** [comment]
We're using clang 3.8.0 compiled from upstream. See https://bugzilla.mozilla.org/show_bug.cgi?id=1262781 for more details.

**Comment by jasone** [comment]
Ahh, gotcha.  I'm going to keep this open so we can keep track of what are probably worthwhile cleanups, but given that I'm hoping to release 4.3.0 within 24 hours, I'd like to punt it to the 5.0.0 milestone.  Do you agree that this is a safe approach?

**Comment by rvandermeulen** [comment]
Sounds fine to me!

**Comment by madscientist** [comment]
We are building on Linux with GCC 6.2.0 and `-Wall -Wformat-security -Wtype-limits -Werror -Wno-strict-aliasing -Wno-unused-function -std=gnu99 -g -O2` and we get these issues in `jemalloc.` (all other files compile cleanly, at least for jemalloc proper...  not sure about the tests):

```
./jemalloc/src/jemalloc.c: In function 'malloc_conf_init':
./jemalloc/src/jemalloc.c:1232:27: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     CONF_HANDLE_SIZE_T(opt_quarantine, "quarantine",
                           ^
./jemalloc/src/jemalloc.c:1232:73: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     CONF_HANDLE_SIZE_T(opt_quarantine, "quarantine",
                                                                         ^
./jemalloc/src/jemalloc.c:1269:27: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     CONF_HANDLE_SIZE_T(opt_lg_prof_sample,
                           ^
./jemalloc/src/jemalloc.c:1269:249: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     CONF_HANDLE_SIZE_T(opt_lg_prof_sample,
                                                                                                                                                                                                                                                         ^
./jemalloc/src/jemalloc.c: In function 'xallocx':
./jemalloc/src/jemalloc.c:2546:8: error: self-comparison always evaluates to true [-Werror=tautological-compare]
  JEMALLOC_VALGRIND_REALLOC(false, tsd_tsdn(tsd), ptr, usize, false, ptr,
        ^~
cc1: all warnings being treated as errors
```

We've been adding `-Wno-type-limits -Wno-tautological-compare` to our jemalloc builds to work around this.

**Comment by jasone** [comment]
Progress: 87004d238cc8db5ea531ef1900a5e6386ccd3daf, 72c587a411050d3283052ebfccf3cc64803f2152, 84ae60357702bcb9be9584ca1d727fb53ec0491c, and 8f61fdedb908c29905103b22dda32ceb29cd8ede are backports from the dev branch.

**Comment by rvandermeulen** [comment]
Looking a lot better!

On MSVC2015u3, I only see a single warning now, and only for Win64 builds.
src/tcache.c(522): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)

Unfortunately, Android and OSX builds are currently broken from 45f83a2, so I'm not sure how they're looking.

**Comment by jasone** [comment]
The MSVC warning is fixed in 6468dd52f3049c3a792ab8a9eb8ce53227523c0b.  Thanks for pointing it out!

**Comment by jasone** [comment]
I tried to reproduce the clang warnings with 3.8.1 on a 32-bit OpenSUSE Tumbleweed system, but no warnings were generated.

  ```clang version 3.8.1 (tags/RELEASE_381/final 273405)```

Is there something about compiler versions that makes this an insufficient surrogate for the 3.8.0-based OS X builds?

**Comment by rvandermeulen** [comment]
In the past, I'd been looking for warnings by just looking through the logs. It occurred to me that Werror would have made my life much easier :)

Testing rev 8e3fb7f with Werror on, I get the below failure across all platforms. Looks like util.c and assert.h aren't getting along?
src/util.c:5:0: error: "assert" redefined [-Werror]
src/util.c:12:0: error: "not_reached" redefined [-Werror]
src/util.c:20:0: error: "not_implemented" redefined [-Werror]

On Android builds, I additionally see:
src/jemalloc.c:1232:327: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
src/jemalloc.c:1232:527: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
src/jemalloc.c:1269:335: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
src/jemalloc.c:1269:557: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
src/jemalloc.c:1399:2: error: implicit declaration of function 'pthread_atfork' [-Werror=implicit-function-declaration]

Looks like some of those were already noted in madscientist's comment yesterday. I do still see the OSX warnings noted in the first comment too, though. I don't know offhand why your surrogate system isn't showing them :(

**Comment by jasone** [comment]
Fixes for the warnings reported by @madscientist:
- dev: aec5a051e8848f06aa041c9ebfc092a2626356fc
- rc-4.4.0: 3ea838d2a20f036ea0d1424262b788fc23686746, 0d6a472db9cb4bcd0406b1770822ee5cc895a7d2

I was unable to reproduce the one caused by ```JEMALLOC_VALGRIND_REALLOC()```, but AFAICT 0d6a472db9cb4bcd0406b1770822ee5cc895a7d2 should fix it.

**Comment by jasone** [comment]
I've fixed everything I can reproduce or guess at solutions for.  Unresolved:
- The clang 3.8.0 warnings on OS do not reproduce for me.  I even tried clang 3.8 and 3.9 from MacPorts.  Note that the line numbers in the original report look really screwy (all on line 70, with huge column numbers?).  I've looked through all the code related to ```arena_chunk_map_misc_t``` variables and can't come up with any plausible explanations for the warnings.
- The ```src/util.c``` errors don't reproduce for me on any platform.

@rvandermeulen, unless you can provide additional information that allows me to understand how these warnings/errors are occurring, I'm going to have to call it good enough.

**Comment by rvandermeulen** [comment]
I'm able to fix the util.c warnings with the patch below:
https://hg.mozilla.org/try/rev/e4cdf8b9cfd5679701cb1c6b4a2826a946e2ddf0

That gets a Werror run mostly clean. Not sure what the story is with those clang warnings, but they don't seem to be fatal to a Werror run, so meh.

I am still seeing the pthread_atfork warning on Android, though. I wonder if the NDK we're using doesn't support it? That'd be a bit surprising, though, since we're using "Android SDK 6.0 / API 23", "Android tools r24.4", "Android build tools 23.0.3", "Android Support Repository (Support Library 23.0.1)", and "Google Support Repository (Google Play Services 8.1.0)" for our builds and we're targeting API15+.

src/jemalloc.c:1417:2: error: implicit declaration of function 'pthread_atfork' [-Werror=implicit-function-declaration]

Maybe it is a Mozilla-specific issue, though. I'll note that we have some Android-related pthread_atfork hackery in our tree currently.
https://dxr.mozilla.org/mozilla-central/source/memory/replace/jemalloc/moz.build#12

**Comment by jasone** [comment]
Interesting, how is it that ```assert```, ```not_reached```, and ```not_implemented``` are already defined before any headers have been included?  ```-Dassert=...``` command line arguments?

**Comment by rvandermeulen** [comment]
None that I can see.

**Comment by jasone** [comment]
Okay, I'll add a feature test for ```pthread_atfork()```, but I'm going to leave ```src/util.c``` alone since I can't see anything wrong with it or the build system that would cause the warnings you're seeing.

**Comment by jasone** [comment]
```pthread_atfork(3)``` feature test:
- dev: 5234be21333e341252ed7223570d790970694d80
- rc-4.4.0: 949a27fc329e6a55a94857a401765d017f13f8ff
